version: "3.9"

services:
  pgbackup:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: pgbackup
    depends_on:
      - postgres
    restart: always
    environment:
      USER_LOGIN: admin
      USER_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
    ports:
    - 8080:8080
  
  postgres:
    image: postgres:16
    container_name: postgres
    command: postgres -c jit=off
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
    # healthcheck:
    #     test: pg_isready -U admin -d dev
    #     interval: 15s
    #     timeout: 5s
    #     retries: 3
    # volumes:
    #   - /dbdata_test:/var/lib/postgresql/data/
    # ports:
    #   - 5433:5432