services:
  pgbackup:
    build:
      context: src
      args:
        VERSION: dev
    container_name: pgbackup
    restart: always
    environment:
      JWT_KEY: very_secret_string
      AES_KEY: key3456789012345
    volumes:
      - ./dumps:/app/dumps:rw
      - ./data:/app/data:rw
    ports:
    - 8080:8080
  