FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY . /build

RUN go build .

FROM alpine

RUN apk --update --no-cache add postgresql-client

WORKDIR /app

COPY --from=builder /build/pgbackup /app

COPY templates/ /app/templates/
COPY static/ /app/static/

VOLUME [ "/app/data" ]
VOLUME [ "/app/dumpls" ]

EXPOSE 8080

ENTRYPOINT [ "./pgbackup" ]
