version: "3.9"

services:
  pgbackup:
    build:
      context: .
      args:
        - USER_DOCKER=pgbackup
        - UID_DOCKER=10000
    container_name: pgbackup
    restart: always
    environment:
      USER_LOGIN: pgbackup
      USER_PASSWORD: pgbackup
    volumes:
      - ./dumps:/app/dumps:rw
      - ./data:/app/data:rw
    ports:
    - 8080:8080
  