name: Release PgBackup on DockerHub

on:
  push:
      paths-ignore:
        # - '.github/**'
        - 'README.md'
        - 'Dockerfile'
        - docker-compose.yaml
      branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        # options: --privileged --shm-size=2g
        # volumes:
        #   - /var/run/docker.sock:/var/run/docker.sock:ro
    # container:
    #   image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install
        run: apt update && apt install -y make

      - name: Build pgbackup
        run: make release version=$(cat version.txt)

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_REGISTRY_LOGIN}} -p ${{secrets.DOCKER_REGISTRY_PWD}}
      
      - name: Push to DockerHub
        run: |
          make push version=$(cat version.txt)
          docker logout
