name: Release PgBackup on DockerHub

on:
  push:
      paths-ignore:
        # - '.github/**'
        - 'README.md'
        - 'Dockerfile'
        - docker-compose.yaml
      branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Docker
        run: apt update && apt-get install -y docker.io

      - name: Build pgbackup
        run: make release version=$(cat version)
      
      - name: Push to DockerHub
        run: |
          docker login -u ${{secrets.DOCKER_REGISTRY_LOGIN}} -p ${{secrets.DOCKER_REGISRTY_PWD}}
          make push version=$(cat version)
          docker logout
